// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/keeee21/commitly/api/repository (interfaces: IUserRepository)

package mocks

import (
	"context"

	"github.com/keeee21/commitly/api/models"
)

// MockUserRepository is a mock of IUserRepository interface.
type MockUserRepository struct {
	FindByIDFunc           func(ctx context.Context, id uint64) (*models.User, error)
	FindByGithubUserIDFunc func(ctx context.Context, githubUserID uint64) (*models.User, error)
	FindAllFunc            func(ctx context.Context) ([]models.User, error)
	CreateFunc             func(ctx context.Context, user *models.User) error
	UpdateFunc             func(ctx context.Context, user *models.User) error
}

func (m *MockUserRepository) FindByID(ctx context.Context, id uint64) (*models.User, error) {
	if m.FindByIDFunc != nil {
		return m.FindByIDFunc(ctx, id)
	}
	return nil, nil
}

func (m *MockUserRepository) FindByGithubUserID(ctx context.Context, githubUserID uint64) (*models.User, error) {
	if m.FindByGithubUserIDFunc != nil {
		return m.FindByGithubUserIDFunc(ctx, githubUserID)
	}
	return nil, nil
}

func (m *MockUserRepository) Create(ctx context.Context, user *models.User) error {
	if m.CreateFunc != nil {
		return m.CreateFunc(ctx, user)
	}
	return nil
}

func (m *MockUserRepository) Update(ctx context.Context, user *models.User) error {
	if m.UpdateFunc != nil {
		return m.UpdateFunc(ctx, user)
	}
	return nil
}

func (m *MockUserRepository) FindAll(ctx context.Context) ([]models.User, error) {
	if m.FindAllFunc != nil {
		return m.FindAllFunc(ctx)
	}
	return nil, nil
}
